apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-cms
provisioner: csi-cvmfsplugin
parameters:
  repository: cms.cern.ch
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-cms-opendata-conddb
provisioner: csi-cvmfsplugin
parameters:
  repository: cms-opendata-conddb.cern.ch
