apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: higgsto4leptons-
spec:
  entrypoint: level3

  volumeClaimTemplates:  #define volume, same syntax as k8s Pod spec
  - metadata:
      name: pvc-cvmfs-cms
    spec:
      accessModes:
      - ReadOnlyMany
      resources:
        requests:
          storage: 5Gi
      storageClassName: csi-cvmfs-cms
  - metadata:
      name: pvc-cvmfs-cms-opendata-conddb
    spec:
      accessModes:
      - ReadOnlyMany
      resources:
        requests:
          storage: 5Gi
      storageClassName: csi-cvmfs-cms-opendata-conddb
  - metadata:
      name: pvc-cephfs-cms
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-cephfs-cms

  # This spec contains three templates:
  # - level3 described the overall workflow (using dag tasks)
  # - cmssw-step1 and cmssw-step2 contain the commands to be run
  templates:
  - name: level3
    # Using dag instead of steps here
    dag:
      tasks:
      - name: step1-data
        template: cmssw-step1
        arguments:
          parameters:
          - name: command
            value: "demoanalyzer_cfg_level3data.py"
      - name: step1-mc
        template: cmssw-step1
        arguments:
          parameters:
          - name: command
            value: "demoanalyzer_cfg_level3MC.py"
      - name: step2
        dependencies: [step1-mc, step1-data]
        template: cmssw-step2
        arguments:
          parameters:
          - name: command
            value: "M4Lnormdatall_lvl3.cc"

  # This is the template for running CMSSW
  - name: cmssw-step1
    inputs:
      parameters:
      - name: command
    script:
      image: clelange/cmssw-slc6-only
      volumeMounts:
        - mountPath: /cvmfs/cms.cern.ch
          name: pvc-cvmfs-cms
        - mountPath: /cvmfs/cms-opendata-conddb.cern.ch
          name: pvc-cvmfs-cms-opendata-conddb
        - mountPath: /mnt/vol
          name: pvc-cephfs-cms
      command: [bash]
      source: |
        sudo chown $USER /mnt/vol
        echo "::: Setting up CMS environment..."
        source /cvmfs/cms.cern.ch/cmsset_default.sh
        echo "::: Setting up CMS environment... [done]"
        scramv1 project CMSSW_5_3_32
        cd CMSSW_5_3_32/src || exit
        eval `scramv1 runtime -sh`
        git clone git://github.com/cms-opendata-analyses/HiggsExample20112012.git || exit
        scram b || exit
        cd HiggsExample20112012/Level3 || exit
        cmsRun {{inputs.parameters.command}} || exit
        cp *.root /mnt/vol
        ls -l /mnt/vol

  # This template produces the plot
  - name: cmssw-step2
    inputs:
      parameters:
      - name: command
    script:
      image: clelange/cmssw-slc6-only
      volumeMounts:
        - mountPath: /cvmfs/cms.cern.ch
          name: pvc-cvmfs-cms
        - mountPath: /cvmfs/cms-opendata-conddb.cern.ch
          name: pvc-cvmfs-cms-opendata-conddb
        - mountPath: /mnt/vol
          name: pvc-cephfs-cms
      command: [bash]
      source: |
        sudo chown $USER /mnt/vol
        export DISPLAY=localhost:0.0
        echo "::: Setting up CMS environment..."
        source /cvmfs/cms.cern.ch/cmsset_default.sh
        echo "::: Setting up CMS environment... [done]"
        scramv1 project CMSSW_5_3_32
        cd CMSSW_5_3_32/src || exit
        eval `scramv1 runtime -sh`
        git clone git://github.com/cms-opendata-analyses/HiggsExample20112012.git || exit
        cd HiggsExample20112012/Level3 || exit
        cp /mnt/vol/*.root .
        root -b -l {{inputs.parameters.command}}
        cp mass4l_combine_userlvl3.pdf /mnt/vol || exit
        ls /mnt/vol
